export enum UserRole {
    CUSTOMER = 'ROLE_CUSTOMER',
    SUPER_ADMIN = 'ROLE_SUPER_ADMIN',
    ADMIN = 'ROLE_ADMIN',
    MANAGER = 'ROLE_MANAGER',
    STAFF = 'ROLE_STAFF',
    OWNER = 'ROLE_OWNER',
}   